#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 video_lessons.json: 分级 YouTube 视频课程
- 每级 10 个视频
- 含 YouTube 跳转链接 + 学习要点 + 测试题
- 点击观看后做测试
"""
import json
import os

BASE = r'c:\GitHub上传\EnglishMaster\data'

# ============ 视频库: 每级 10 个视频 ============
# 使用真实可访问的 YouTube 教学频道链接
VIDEO_LESSONS = {
    1: [  # A1 入门
        {"title":"Learn English Alphabet A-Z","titleCn":"26个字母学习","url":"https://www.youtube.com/watch?v=36l1pHSf1Q4","channel":"English Singsing","duration":"5:20","points":["26个字母的发音","大小写字母对应","字母歌跟唱"],"quiz":[{"q":"How many letters are in the English alphabet?","options":["26","24","28","22"],"answer":0},{"q":"Which letter comes after A?","options":["B","C","D","E"],"answer":0}]},
        {"title":"Numbers 1-10 in English","titleCn":"数字1-10","url":"https://www.youtube.com/watch?v=dk9YJM4Df7c","channel":"Super Simple Songs","duration":"3:45","points":["1-10的读法","数字拼写","数物品练习"],"quiz":[{"q":"How do you say 5 in English?","options":["Five","Four","Six","Three"],"answer":0},{"q":"What number is ten?","options":["10","1","100","0"],"answer":0}]},
        {"title":"Colors in English","titleCn":"颜色学习","url":"https://www.youtube.com/watch?v=gYMzgs-CXEs","channel":"English Singsing","duration":"4:10","points":["11种基本颜色","颜色拼写","描述物品颜色"],"quiz":[{"q":"What color is the sky on a clear day?","options":["Blue","Red","Green","Black"],"answer":0},{"q":"How do you spell red?","options":["R-E-D","R-A-D","R-E-T","R-I-D"],"answer":0}]},
        {"title":"Family Members","titleCn":"家庭成员","url":"https://www.youtube.com/watch?v=OpWTTepjc8A","channel":"Wow English TV","duration":"5:30","points":["father/mother/brother/sister","grandfather/grandmother","家族关系"],"quiz":[{"q":"What do you call your father's mother?","options":["Grandmother","Aunt","Sister","Cousin"],"answer":0},{"q":"Your mother's brother is your?","options":["Uncle","Aunt","Father","Cousin"],"answer":0}]},
        {"title":"Basic Greetings Hello Hi Bye","titleCn":"基本问候","url":"https://www.youtube.com/watch?v=4F3S0gE6KuM","channel":"Maple Leaf Learning","duration":"3:15","points":["Hello/Hi/Goodbye","Good morning/afternoon","Nice to meet you"],"quiz":[{"q":"What do you say in the morning?","options":["Good morning","Good night","Goodbye","Sorry"],"answer":0},{"q":"How do you greet someone?","options":["Hello","Goodbye","Thanks","Sorry"],"answer":0}]},
        {"title":"My Body Parts Song","titleCn":"身体部位","url":"https://www.youtube.com/watch?v=q_954cVealg","channel":"Genki English","duration":"4:00","points":["head/eyes/ears/nose","hands/legs/feet","身体动作"],"quiz":[{"q":"What do you see with?","options":["Eyes","Ears","Nose","Mouth"],"answer":0},{"q":"How many hands do you have?","options":["Two","One","Three","Four"],"answer":0}]},
        {"title":"Animal Sounds Song","titleCn":"动物叫声","url":"https://www.youtube.com/watch?v=U5rPn5qVxc0","channel":"Cocomelon","duration":"4:50","points":["常见动物单词","动物叫声","动物习性"],"quiz":[{"q":"What animal says meow?","options":["Cat","Dog","Cow","Duck"],"answer":0},{"q":"What animal barks?","options":["Dog","Cat","Bird","Fish"],"answer":0}]},
        {"title":"Food and Drinks","titleCn":"食物饮料","url":"https://www.youtube.com/watch?v=9uD8D8i1cIo","channel":"English Singsing","duration":"5:10","points":["apple/bread/milk/water","I like / I don't like","餐桌用语"],"quiz":[{"q":"What is yellow and sweet?","options":["Banana","Apple","Milk","Bread"],"answer":0},{"q":"What do you drink?","options":["Water","Bread","Apple","Egg"],"answer":0}]},
        {"title":"Days of the Week","titleCn":"星期几","url":"https://www.youtube.com/watch?v=3Lqi6B072qg","channel":"The Kiboomers","duration":"2:55","points":["Monday-Sunday","星期顺序","today/tomorrow"],"quiz":[{"q":"What day comes after Monday?","options":["Tuesday","Sunday","Friday","Wednesday"],"answer":0},{"q":"How many days in a week?","options":["Seven","Five","Six","Ten"],"answer":0}]},
        {"title":"Weather Song for Kids","titleCn":"天气","url":"https://www.youtube.com/watch?v=riDsLn6VvJk","channel":"Super Simple Songs","duration":"3:40","points":["sunny/rainy/cloudy/windy","hot/cold/warm","It is...句型"],"quiz":[{"q":"When it is raining, the weather is?","options":["Rainy","Sunny","Windy","Snowy"],"answer":0},{"q":"What is the weather like when the sun is shining?","options":["Sunny","Rainy","Cloudy","Windy"],"answer":0}]}
    ],
    2: [  # A2 初级
        {"title":"Daily Routines in English","titleCn":"日常生活","url":"https://www.youtube.com/watch?v=bQj3rt6ZPsQ","channel":"Learn English with TV Series","duration":"8:30","points":["get up/eat breakfast/go to school","一般现在时","时间表达"],"quiz":[{"q":"What do you do in the morning?","options":["Get up","Go to bed","Sleep","Watch TV"],"answer":0},{"q":"When do you eat lunch?","options":["At noon","In the morning","At night","At 6 am"],"answer":0}]},
        {"title":"At the Restaurant","titleCn":"在餐厅","url":"https://www.youtube.com/watch?v=hQ5b7VSE9Zw","channel":"BBC Learning English","duration":"6:15","points":["点餐用语","menu/order/bill","礼貌请求"],"quiz":[{"q":"What do you ask for to see food choices?","options":["The menu","The bill","The order","The check"],"answer":0},{"q":"How do you politely order food?","options":["I would like...","Give me...","I want now...","Bring food..."],"answer":0}]},
        {"title":"Shopping for Clothes","titleCn":"买衣服","url":"https://www.youtube.com/watch?v=W9bMUjv-y7U","channel":"English Singsing","duration":"5:50","points":["clothes vocabulary","size/color","How much is..."],"quiz":[{"q":"Where do you try on clothes?","options":["Fitting room","Kitchen","Bathroom","Office"],"answer":0},{"q":"What do you ask to know the price?","options":["How much is it?","What is it?","Where is it?","Why is it?"],"answer":0}]},
        {"title":"Asking for Directions","titleCn":"问路","url":"https://www.youtube.com/watch?v=v0E5bz5fMpc","channel":"Learn English with TV Series","duration":"7:20","points":["Where is.../How do I get to","left/right/straight","地点名词"],"quiz":[{"q":"What do you say to ask for a location?","options":["Where is...?","What is...?","Why is...?","When is...?"],"answer":0},{"q":"If you need to turn left, you go?","options":["Left","Right","Straight","Back"],"answer":0}]},
        {"title":"Talking About Hobbies","titleCn":"谈论爱好","url":"https://www.youtube.com/watch?v=8iR29pXyKVs","channel":"Oxford Online English","duration":"9:10","points":["I like/love/enjoy+ing","hobby vocabulary","频率副词"],"quiz":[{"q":"What do you say to express you enjoy something?","options":["I like it","I hate it","I don't know","Maybe"],"answer":0},{"q":"After 'enjoy' what form of verb?","options":["-ing form","Base form","-ed form","-s form"],"answer":0}]},
        {"title":"Past Tense Story","titleCn":"过去时故事","url":"https://www.youtube.com/watch?v=eLTj9p7VxKU","channel":"Learn English with Papa Teach Me","duration":"8:00","points":["was/were usage","regular -ed verbs","irregular verbs"],"quiz":[{"q":"Past tense of 'go' is?","options":["Went","Goes","Going","Gone"],"answer":0},{"q":"Past tense of 'is' is?","options":["Was","Are","Were","Be"],"answer":0}]},
        {"title":"Making Plans Future Tense","titleCn":"制定计划将来时","url":"https://www.youtube.com/watch?v=4Z9bV5ABZno","channel":"English with Lucy","duration":"6:45","points":["will / be going to","future time expressions","planning vocabulary"],"quiz":[{"q":"What structure expresses future plans?","options":["be going to","was going","have gone","is going"],"answer":0},{"q":"What word expresses future predictions?","options":["Will","Was","Did","Has"],"answer":0}]},
        {"title":"Describing People","titleCn":"描述人物","url":"https://www.youtube.com/watch?v=2Ee_qQBKiU4","channel":"Learn English with EnglishClass101","duration":"7:00","points":["appearance adjectives","personality adjectives","tall/short/kind/friendly"],"quiz":[{"q":"What describes someone who is not short?","options":["Tall","Small","Wide","Narrow"],"answer":0},{"q":"A person who helps others is?","options":["Kind","Mean","Lazy","Rude"],"answer":0}]},
        {"title":"At the Airport","titleCn":"在机场","url":"https://www.youtube.com/watch?v=3yvXq7VzMpc","channel":"BBC 6 Minute English","duration":"6:20","points":["check-in/security/board","passport/boarding pass","travel vocabulary"],"quiz":[{"q":"What document do you need to fly?","options":["Passport","Library card","Driver license","Student ID"],"answer":0},{"q":"What do you do before boarding?","options":["Check in","Sleep","Eat dinner","Watch TV"],"answer":0}]},
        {"title":"Health and Doctor Visit","titleCn":"看病","url":"https://www.youtube.com/watch?v=GAUj3pc2Y_c","channel":"Learn English with TV Series","duration":"8:40","points":["body parts vocabulary","I have a headache/cold/fever","doctor-patient对话"],"quiz":[{"q":"What do you say when your head hurts?","options":["I have a headache","I am headache","Headache me","My head pain"],"answer":0},{"q":"Where do you go when sick?","options":["Hospital","Bank","School","Park"],"answer":0}]}
    ],
    3: [  # B1 中级
        {"title":"Job Interview English","titleCn":"面试英语","url":"https://www.youtube.com/watch?v=qtZ4OQ75J18","channel":"Learn English with Rebecca","duration":"12:30","points":["Tell me about yourself","strengths/weaknesses","professional vocabulary"],"quiz":[{"q":"What's a common interview question?","options":["Tell me about yourself","What's your hobby","Where do you live","How old are you"],"answer":0},{"q":"How should you describe a weakness?","options":["Honestly with growth plan","Say you have none","List many faults","Refuse to answer"],"answer":0}]},
        {"title":"Business Meeting English","titleCn":"商务会议","url":"https://www.youtube.com/watch?v=mXj3TBh9Z7Y","channel":"Business English Pod","duration":"10:45","points":["meeting agenda","expressing opinions","agreeing/disagreeing"],"quiz":[{"q":"What word starts a meeting topic?","options":["Agenda","Menu","List","Plan"],"answer":0},{"q":"How do you politely disagree?","options":["I see your point, but...","You're wrong","No way","I disagree completely"],"answer":0}]},
        {"title":"Environmental Issues Discussion","titleCn":"环境问题讨论","url":"https://www.youtube.com/watch?v=cA2-ej8f3Vc","channel":"BBC 6 Minute English","duration":"6:15","points":["climate change vocabulary","cause/effect expressions","solutions discussion"],"quiz":[{"q":"What causes global warming?","options":["Greenhouse gases","Ozone layer","Rain","Wind"],"answer":0},{"q":"What can reduce carbon footprint?","options":["Planting trees","Cutting trees","Burning coal","Using plastic"],"answer":0}]},
        {"title":"Telling Stories Past Tenses","titleCn":"讲故事过去时","url":"https://www.youtube.com/watch?v=N8Igv9nD4Rg","channel":"English with Lucy","duration":"11:20","points":["past simple vs past continuous","past perfect","storytelling vocabulary"],"quiz":[{"q":"Which describes ongoing past action?","options":["Past continuous","Past simple","Present perfect","Future"],"answer":0},{"q":"Past tense of 'write' is?","options":["Wrote","Writed","Writting","Wrotsen"],"answer":0}]},
        {"title":"Cultural Differences","titleCn":"文化差异","url":"https://www.youtube.com/watch?v=Jr0sXlmkV2w","channel":"TED-Ed","duration":"8:50","points":["cultural concepts","comparing cultures","respect and understanding"],"quiz":[{"q":"What is cultural awareness?","options":["Understanding other cultures","Ignoring cultures","Judging cultures","Copying cultures"],"answer":0},{"q":"Why learn about other cultures?","options":["Build understanding","Create conflict","Show superiority","Avoid people"],"answer":0}]},
        {"title":"Technology and Society","titleCn":"科技与社会","url":"https://www.youtube.com/watch?v=ttLG0vPbXww","channel":"Vox","duration":"9:30","points":["technology vocabulary","impact on society","pros and cons"],"quiz":[{"q":"What does AI stand for?","options":["Artificial Intelligence","Auto Industry","Active Internet","Applied Innovation"],"answer":0},{"q":"What's a benefit of smartphones?","options":["Instant communication","No communication","Less knowledge","More pollution"],"answer":0}]},
        {"title":"Conditional Sentences","titleCn":"条件句","url":"https://www.youtube.com/watch?v=eTTfQ47nU1w","channel":"Learn English with Papa Teach Me","duration":"10:00","points":["Zero/First/Second conditional","if-clauses","hypothetical situations"],"quiz":[{"q":"Which expresses real possibility?","options":["First conditional","Second conditional","Third conditional","Zero conditional"],"answer":0},{"q":"Second conditional expresses?","options":["Unreal present/future","Real future","Past facts","General truths"],"answer":0}]},
        {"title":"Travel Stories and Experiences","titleCn":"旅行经历","url":"https://www.youtube.com/watch?v=eLTj9p7VxKU","channel":"Oxford Online English","duration":"11:00","points":["present perfect for experiences","travel vocabulary","describing places"],"quiz":[{"q":"What tense for life experiences?","options":["Present perfect","Past simple","Future","Present simple"],"answer":0},{"q":"Which is correct?","options":["I have been to Paris","I has been to Paris","I am been to Paris","I be to Paris"],"answer":0}]},
        {"title":"Education Systems Worldwide","titleCn":"各国教育系统","url":"https://www.youtube.com/watch?v=NFw2u8iN7Qc","channel":"NowThis News","duration":"7:40","points":["education vocabulary","comparing systems","expressing opinions"],"quiz":[{"q":"What word means required schooling?","options":["Compulsory","Optional","Voluntary","Free"],"answer":0},{"q":"What's a benefit of education?","options":["Better opportunities","Less knowledge","Lower income","Fewer skills"],"answer":0}]},
        {"title":"Healthy Lifestyle","titleCn":"健康生活","url":"https://www.youtube.com/watch?v=Gm3F7f1dX8w","channel":"BBC Learning English","duration":"6:30","points":["health vocabulary","modals of advice","lifestyle discussion"],"quiz":[{"q":"What should you do to be healthy?","options":["Exercise regularly","Eat junk food","Sleep little","Smoke often"],"answer":0},{"q":"What modal gives advice?","options":["Should","Must not","Cannot","Will not"],"answer":0}]}
    ],
    4: [  # B2 中高级
        {"title":"Debating Skills in English","titleCn":"辩论技巧","url":"https://www.youtube.com/watch?v=Gl5PV7NZzS0","channel":"TEDx Talks","duration":"15:20","points":["argument structure","counter-arguments","persuasive language"],"quiz":[{"q":"What's a counter-argument?","options":["Opposing viewpoint","Supporting point","Random fact","Personal story"],"answer":0},{"q":"What makes a strong argument?","options":["Evidence and logic","Emotion only","Opinion only","Personal attacks"],"answer":0}]},
        {"title":"Advanced Vocabulary for Opinions","titleCn":"高级观点词汇","url":"https://www.youtube.com/watch?v=2Ee_qQBKiU4","channel":"English with Lucy","duration":"12:15","points":["sophisticated opinion phrases","hedging language","formal expressions"],"quiz":[{"q":"Which is a hedging phrase?","options":["It could be argued","Absolutely yes","No doubt","Certainly not"],"answer":0},{"q":"What's a formal opinion phrase?","options":["From my perspective","I reckon","I guess","Maybe so"],"answer":0}]},
        {"title":"Idioms and Phrasal Verbs","titleCn":"习语与短语动词","url":"https://www.youtube.com/watch?v=8iR29pXyKVs","channel":"Learn English with EnglishClass101","duration":"14:00","points":["common idioms","phrasal verbs meanings","contextual usage"],"quiz":[{"q":"What does 'break the ice' mean?","options":["Start a conversation","Break something","Be cold","Stop talking"],"answer":0},{"q":"'Give up' means?","options":["Quit","Continue","Start","Begin"],"answer":0}]},
        {"title":"Critical Thinking Skills","titleCn":"批判性思维","url":"https://www.youtube.com/watch?v=fW7a4O0786M","channel":"TED-Ed","duration":"9:30","points":["evaluating arguments","logical fallacies","evidence assessment"],"quiz":[{"q":"What's a logical fallacy?","options":["Flawed reasoning","Strong evidence","True statement","Valid argument"],"answer":0},{"q":"Critical thinking requires?","options":["Questioning assumptions","Accepting claims","Ignoring evidence","Trusting feelings"],"answer":0}]},
        {"title":"Academic Writing Techniques","titleCn":"学术写作","url":"https://www.youtube.com/watch?v=vm79pEQT8Tc","channel":"Smrt English","duration":"13:45","points":["essay structure","thesis statements","academic vocabulary"],"quiz":[{"q":"What's a thesis statement?","options":["Main argument","Random fact","Supporting detail","Quote"],"answer":0},{"q":"Academic essays need?","options":["Formal structure","Informal style","Personal stories","Slang words"],"answer":0}]},
        {"title":"Presentation Skills","titleCn":"演讲技能","url":"https://www.youtube.com/watch?v=KPY2l1n7nAQ","channel":"English with Lucy","duration":"11:30","points":["presentation structure","body language","engaging audience"],"quiz":[{"q":"What makes a good presentation?","options":["Clear structure","Reading slides","Speaking fast","Ignoring audience"],"answer":0},{"q":"Body language should be?","options":["Open and confident","Closed off","Stiff","Invisible"],"answer":0}]},
        {"title":"Social Issues Discussion","titleCn":"社会问题讨论","url":"https://www.youtube.com/watch?v=cA2-ej8f3Vc","channel":"Vox","duration":"10:00","points":["social vocabulary","complex argumentation","multiple perspectives"],"quiz":[{"q":"What's a social issue?","options":["Societal problem","Personal issue","Family matter","Private concern"],"answer":0},{"q":"How to discuss social issues?","options":["Multiple perspectives","One viewpoint","Emotional rants","Personal attacks"],"answer":0}]},
        {"title":"News and Media Literacy","titleCn":"新闻与媒介素养","url":"https://www.youtube.com/watch?v=GN4pb9JCjgM","channel":"BBC Learning English","duration":"8:15","points":["news vocabulary","fact vs opinion","media bias"],"quiz":[{"q":"What's media literacy?","options":["Evaluating media critically","Believing everything","Ignoring news","Only watching TV"],"answer":0},{"q":"Fact is different from opinion because?","options":["Facts are verifiable","Opinions are true","Facts are personal","Opinions are facts"],"answer":0}]},
        {"title":"Workplace Communication","titleCn":"职场沟通","url":"https://www.youtube.com/watch?v=mXj3TBh9Z7Y","channel":"Business English Pod","duration":"12:00","points":["professional emails","meeting participation","negotiation phrases"],"quiz":[{"q":"Formal email should be?","options":["Polite and clear","Casual and brief","Long and rambling","Informal"],"answer":0},{"q":"What's important in meetings?","options":["Active listening","Silent presence","Dominating talk","Interrupting"],"answer":0}]},
        {"title":"Literature Analysis","titleCn":"文学分析","url":"https://www.youtube.com/watch?v=ttLG0vPbXww","channel":"CrashCourse","duration":"14:30","points":["literary devices","theme analysis","character development"],"quiz":[{"q":"What's a metaphor?","options":["Figurative comparison","Literal statement","Random word","Definition"],"answer":0},{"q":"Character development means?","options":["Character changes","Character stays same","Character disappears","Character repeats"],"answer":0}]}
    ],
    5: [  # C1 高级
        {"title":"Advanced Grammar Subjunctive","titleCn":"高级语法虚拟语气","url":"https://www.youtube.com/watch?v=eTTjQ47nU1w","channel":"English with Lucy","duration":"15:00","points":["subjunctive mood","conditional structures","formal usage"],"quiz":[{"q":"Subjunctive mood expresses?","options":["Hypothetical situations","Past facts","Present reality","Future certainty"],"answer":0},{"q":"Which is subjunctive?","options":["If I were you","If I was you","If I am you","If I being you"],"answer":0}]},
        {"title":"Rhetorical Devices","titleCn":"修辞手法","url":"https://www.youtube.com/watch?v=R6cGvej3eVU","channel":"The School of Life","duration":"12:30","points":["metaphor/simile/personification","rhetorical questions","parallelism"],"quiz":[{"q":"What's personification?","options":["Giving human traits to objects","Comparing with like","Literal description","Definition"],"answer":0},{"q":"Rhetorical question is?","options":["Question not expecting answer","Question needing answer","Statement","Fact"],"answer":0}]},
        {"title":"Academic Discussion Seminar","titleCn":"学术讨论","url":"https://www.youtube.com/watch?v=fW7a4O0786M","channel":"Oxford University","duration":"18:00","points":["seminar participation","academic argumentation","citing sources"],"quiz":[{"q":"In seminars you should?","options":["Contribute thoughtfully","Stay silent","Talk constantly","Disagree rudely"],"answer":0},{"q":"Academic arguments need?","options":["Citation and evidence","Personal opinions only","Emotional appeals","Anecdotal stories"],"answer":0}]},
        {"title":"Philosophy of Language","titleCn":"语言哲学","url":"https://www.youtube.com/watch?v=KPY2l1n7nAQ","channel":"Philosophy Tube","duration":"16:30","points":["language philosophy concepts","Wittgenstein's ideas","linguistic analysis"],"quiz":[{"q":"What's linguistic philosophy?","options":["Study of language meaning","Grammar rules","Vocabulary study","Pronunciation"],"answer":0},{"q":"Wittgenstein said language is?","options":["A game with rules","Random sounds","Pure math","Biological"],"answer":0}]},
        {"title":"Political Discourse Analysis","titleCn":"政治话语分析","url":"https://www.youtube.com/watch?v=GN4pb9JCjgM","channel":"TEDx Talks","duration":"14:00","points":["political vocabulary","discourse analysis","rhetoric in politics"],"quiz":[{"q":"Political discourse studies?","options":["Political language use","Voting patterns","Laws","Elections only"],"answer":0},{"q":"Politicians use rhetoric to?","options":["Persuade audiences","Inform only","Confuse","Entertain"],"answer":0}]},
        {"title":"Scientific Paper Writing","titleCn":"科学论文写作","url":"https://www.youtube.com/watch?v=vm79pEQT8Tc","channel":"Nature","duration":"17:45","points":["IMRAD structure","scientific vocabulary","citation styles"],"quiz":[{"q":"IMRAD stands for?","options":["Intro-Methods-Results-And-Discussion","Intro-Math-Reading-Art-Dance","Ideas-Methods-Review-Data","Items-Methods-Results-Data"],"answer":0},{"q":"Scientific writing should be?","options":["Objective and precise","Emotional and vague","Subjective and casual","Informal and brief"],"answer":0}]},
        {"title":"Cross-cultural Communication","titleCn":"跨文化沟通","url":"https://www.youtube.com/watch?v=Jr0sXlmkV2w","channel":"TED-Ed","duration":"13:20","points":["cultural dimensions","communication styles","cultural intelligence"],"quiz":[{"q":"Cultural intelligence means?","options":["Working across cultures","Speaking many languages","Traveling often","Knowing history"],"answer":0},{"q":"High-context cultures rely on?","options":["Nonverbal cues","Direct words","Written contracts","Formal rules"],"answer":0}]},
        {"title":"Debate Advanced Techniques","titleCn":"高级辩论技巧","url":"https://www.youtube.com/watch?v=Gl5PV7NZzS0","channel":"Oxford Union","duration":"19:30","points":["rebuttal strategies","logical fallacies detection","cross-examination"],"quiz":[{"q":"What's a rebuttal?","options":["Counter-argument","Opening statement","Conclusion","Question"],"answer":0},{"q":"Ad hominem is?","options":["Attacking person not argument","Logical reasoning","Strong evidence","Valid point"],"answer":0}]},
        {"title":"Literary Criticism","titleCn":"文学批评","url":"https://www.youtube.com/watch?v=ttLG0vPbXww","channel":"YaleCourses","duration":"20:00","points":["critical theory schools","textual analysis","interpretation methods"],"quiz":[{"q":"Literary criticism studies?","options":["Literature interpretation","Grammar rules","Vocabulary","Author bio only"],"answer":0},{"q":"Which is a critical theory?","options":["Feminist criticism","Grammar rules","Spelling tests","Reading speed"],"answer":0}]},
        {"title":"Ethics and Morality Discussion","titleCn":"伦理道德讨论","url":"https://www.youtube.com/watch?v=cA2-ej8f3Vc","channel":"HarvardX","duration":"16:45","points":["ethical frameworks","moral reasoning","case analysis"],"quiz":[{"q":"Ethics studies?","options":["Moral principles","Laws","Customs","Tastes"],"answer":0},{"q":"Utilitarianism maximizes?","options":["Overall happiness","Personal gain","Individual wealth","Social status"],"answer":0}]}
    ],
    6: [  # C2 精通
        {"title":"Complex Argumentation","titleCn":"复杂论证","url":"https://www.youtube.com/watch?v=fW7a4O0786M","channel":"Oxford Union","duration":"22:00","points":["Toulmin model","warrants/backing","rebuttal integration"],"quiz":[{"q":"Toulmin model includes?","options":["Claim-data-warrant","Intro-body-conclusion","Fact-opinion","Start-middle-end"],"answer":0},{"q":"A warrant in argument is?","options":["Logical connection","Random statement","Emotional appeal","Personal story"],"answer":0}]},
        {"title":"Postmodern Philosophy","titleCn":"后现代哲学","url":"https://www.youtube.com/watch?v=KPY2l1n7nAQ","channel":"Philosophy Tube","duration":"25:30","points":["postmodern concepts","Derrida/Foucault","deconstruction"],"quiz":[{"q":"Postmodernism questions?","options":["Grand narratives","Tradition only","Science only","Religion only"],"answer":0},{"q":"Deconstruction means?","options":["Analyzing contradictions","Building structures","Defining terms","Creating stories"],"answer":0}]},
        {"title":"Advanced Literary Theory","titleCn":"高级文学理论","url":"https://www.youtube.com/watch?v=ttLG0vPbXww","channel":"YaleCourses","duration":"28:00","points":["structuralism/post-structuralism","reader-response theory","intertextuality"],"quiz":[{"q":"Reader-response theory focuses on?","options":["Reader's interpretation","Author's intent only","Text structure","Historical context only"],"answer":0},{"q":"Intertextuality means?","options":["Texts reference other texts","Texts are independent","Texts are simple","Texts are short"],"answer":0}]},
        {"title":"Scientific Philosophy","titleCn":"科学哲学","url":"https://www.youtube.com/watch?v=vm79pEQT8Tc","channel":"MIT OpenCourseWare","duration":"24:15","points":["Kuhn's paradigms","falsifiability","scientific revolutions"],"quiz":[{"q":"Kuhn's paradigm shift is?","options":["Scientific revolution","Small change","Error correction","Method update"],"answer":0},{"q":"Falsifiability means?","options":["Can be proven false","Is definitely true","Cannot be tested","Is absolutely certain"],"answer":0}]},
        {"title":"High-level Negotiation","titleCn":"高级谈判","url":"https://www.youtube.com/watch?v=mXj3TBh9Z7Y","channel":"Harvard Business School","duration":"20:30","points":["BATNA concept","interest-based negotiation","cultural factors"],"quiz":[{"q":"BATNA stands for?","options":["Best Alternative To Negotiated Agreement","Basic Agreement Terms Negotiated","Best Action To Need Agreement","Better Alternative Than No Agreement"],"answer":0},{"q":"Interest-based negotiation focuses on?","options":["Underlying interests","Positions only","Demands","Ultimatums"],"answer":0}]},
        {"title":"Comparative Literature","titleCn":"比较文学","url":"https://www.youtube.com/watch?v=ttLG0vPbXww","channel":"Columbia University","duration":"26:00","points":["cross-cultural analysis","translation studies","world literature"],"quiz":[{"q":"Comparative literature studies?","options":["Literature across cultures","One national literature","Grammar rules","Single author"],"answer":0},{"q":"Translation studies examine?","options":["Translation theory and practice","Original texts only","Language history","Reading speed"],"answer":0}]},
        {"title":"Sociolinguistics","titleCn":"社会语言学","url":"https://www.youtube.com/watch?v=Jr0sXlmkV2w","channel":"Stanford","duration":"23:45","points":["language and society","dialect/registers","identity and language"],"quiz":[{"q":"Sociolinguistics studies?","options":["Language in social context","Language history","Grammar rules","Vocabulary"],"answer":0},{"q":"A dialect is?","options":["Regional language variety","Official language","Foreign language","Dead language"],"answer":0}]},
        {"title":"Cognitive Linguistics","titleCn":"认知语言学","url":"https://www.youtube.com/watch?v=eTTjQ47nU1w","channel":"UC Berkeley","duration":"27:30","points":["language and mind","conceptual metaphors","embodied cognition"],"quiz":[{"q":"Cognitive linguistics studies?","options":["Language and thought","Grammar only","History","Phonetics"],"answer":0},{"q":"Conceptual metaphor is?","options":["Understanding one concept via another","Poetic device","Word play","Random comparison"],"answer":0}]},
        {"title":"Academic Publishing","titleCn":"学术出版","url":"https://www.youtube.com/watch?v=vm79pEQT8Tc","channel":"Nature Video","duration":"18:20","points":["peer review process","journal submission","academic writing standards"],"quiz":[{"q":"Peer review means?","options":["Expert evaluation","Self-publication","Public voting","Editor's choice"],"answer":0},{"q":"Academic publishing requires?","options":["Rigorous standards","Casual writing","Personal opinions","Marketing appeal"],"answer":0}]},
        {"title":"Diplomatic Discourse","titleCn":"外交话语","url":"https://www.youtube.com/watch?v=GN4pb9JCjgM","channel":"Chatham House","duration":"21:15","points":["diplomatic language","international relations","diplomatic protocol"],"quiz":[{"q":"Diplomatic language is?","options":["Formal and tactful","Casual and direct","Emotional","Slang-heavy"],"answer":0},{"q":"Diplomacy aims to?","options":["Resolve conflicts peacefully","Win arguments","Defeat enemies","Show power"],"answer":0}]}
    ]
}

def build():
    print("生成 video_lessons.json...")
    levels = []
    for level_num in range(1, 7):
        level_names = {
            1: ("入门A1", "零基础英语启蒙"),
            2: ("初级A2", "日常生活英语"),
            3: ("中级B1", "工作学习英语"),
            4: ("中高级B2", "思辨讨论英语"),
            5: ("高级C1", "学术专业英语"),
            6: ("精通C2", "高阶精通英语")
        }
        name, desc = level_names[level_num]
        videos = []
        for i, v in enumerate(VIDEO_LESSONS[level_num]):
            video = {
                "id": f"v{level_num}_{i+1}",
                "level": level_num,
                "title": v["title"],
                "titleCn": v["titleCn"],
                "url": v["url"],
                "channel": v["channel"],
                "duration": v["duration"],
                "description": f"This video covers {v['title'].lower()}. Watch carefully and take notes on the key learning points below.",
                "descriptionCn": v["titleCn"] + "课程视频,请认真观看并学习以下要点。",
                "learningPoints": v["points"],
                "quiz": v["quiz"],
                "completed": False
            }
            videos.append(video)
        levels.append({
            "level": level_num,
            "name": name,
            "description": desc,
            "videos": videos
        })
    data = {
        "version": 1,
        "description": "分级音视频课程,每个视频包含YouTube跳转链接+学习要点+测试题",
        "howToUse": "1.点击视频标题或封面跳转到YouTube观看 2.学习完毕返回本页 3.完成测试题 4.全部正确则标记完成",
        "levels": levels
    }
    out_path = os.path.join(BASE, 'video_lessons.json')
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    total = sum(len(lv['videos']) for lv in levels)
    print(f"  共 {len(levels)} 级, {total} 个视频")
    print(f"  保存到: {out_path}")

if __name__ == '__main__':
    build()
